### ISSUE TITLE
where is root dir in Meddle ?

### ISSUE THREAD

**Issue by paulanalyst** [JuliaWeb/Meddle.jl#10]
Hi , I try raun Medle , ol is ok only cant find dir for root. Wher put file index.html ?
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f96c23c* (6 days old master)
|__/                   |  x86_64-w64-mingw32

julia> pwd()
"D:\\pawel\\rynek\\WP\\Julia6_WP\\Julia-0.4.0-dev"

julia> readall("index.html")
"haha"

julia> using HttpServer

WARNING: deprecated syntax "[a=>b, ...]" at C:\Users\SAMSUNG2\.julia\v0.4\HttpServer\src\HttpServer.jl:9.
Use "Dict(a=>b, ...)" instead.
WARNING: Dict-based `@docstring` config is deprecated. Use keywords instead.
WARNING: This version of the GnuTLS library (3.2.15) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.

julia> using Meddle

julia>

julia> stack = middleware(DefaultHeaders, URLDecoder, CookieDecoder, FileServer(pwd()), NotFound)
5-element Array{Meddle.Midware,1}:
 Meddle.Midware((anonymous function),Any[],Any[])
 Meddle.Midware((anonymous function),Any[],Any[])
 Meddle.Midware((anonymous function),Any[],Any[])
 Meddle.Midware((anonymous function),Any[],Any[])
 Meddle.Midware((anonymous function),Any[],Any[])

julia> http = HttpHandler((req, res)->Meddle.handle(stack, MeddleRequest(req, Dict{Symbol,Any}()), res))
HttpServer.HttpHandler((anonymous function),TCPServer(init),Dict("error"=>(anonymous function),"listen"=>(anonymou
s function)))

julia>

julia> for event in split("connect read write close error")
           http.events[event] = (event->(client, args...)->println(client.id,": $event"))(event)
       end

julia> http.events["error"] = (client, err)->println(err)
(anonymous function)

julia> http.events["listen"] = (port)->println("Listening on $port...")
(anonymous function)

julia>

julia> server = Server(http)
HttpServer.Server(HttpServer.HttpHandler((anonymous function),TCPServer(init),Dict("error"=>(anonymous function),"
listen"=>(anonymous function),"write"=>(anonymous function),"connect"=>(anonymous function),"close"=>(anonymous fu
nction),"read"=>(anonymous function))),nothing)

julia> run(server, 8000)
Listening on 8000...
1: connect
...
file index is like pwd() but when I call by my broweser: http://localhost:8000/index.html
is nothing. Medlle :
1: connect
MethodError(convert,(Meddle.MeddleRequest,=== Resource ====
resource: /index.html
method: GET
Headers:
    http_major: 1
    Connection: keep-alive
    Host: localhost:8000
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    http_minor: 1
    Accept-Language: pl,en-US;q=0.7,en;q=0.3
    Keep-Alive: 1
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0
    Accept-Encoding: gzip, deflate
data:
=== End Resource ===
,Dict{Symbol,Any}()))
ERROR: MethodError: `convert` has no method matching convert(::Type{Meddle.MeddleRequest}, ::HttpCommon.Request, :
:Dict{Symbol,Any})
This may have arisen from a call to the constructor Meddle.MeddleRequest(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, ::T)

 in call at base.jl:36
 in anonymous at none:1
 in on_message_complete at C:\Users\SAMSUNG2\.julia\v0.4\HttpServer\src\HttpServer.jl:303
 in on_message_complete at C:\Users\SAMSUNG2\.julia\v0.4\HttpServer\src\RequestParser.jl:99
 in http_parser_execute at C:\Users\SAMSUNG2\.julia\v0.4\HttpParser\src\HttpParser.jl:106
 in add_data at C:\Users\SAMSUNG2\.julia\v0.4\HttpServer\src\RequestParser.jl:148
 in process_client at C:\Users\SAMSUNG2\.julia\v0.4\HttpServer\src\HttpServer.jl:267
 in anonymous at task.jl:344
1: write
1: close

**Comment by paulanalyst** [comment]
any hint?
Paul

**Comment by StefanKarpinski** [comment]
This was answered recently on the julia-users mailing list, try taking a look there.

**Comment by paulanalyst** [comment]
Stefan , sorry but I cant find  ...
The answer from Avik 03.03 is not sufficent.
Paul

https://groups.google.com/forum/#!searchin/julia-users/meddle|sort:date

W dniu 2015-03-11 o 15:27, Stefan Karpinski pisze:

**Comment by paulanalyst** [comment]
P.s
nothink abou root dir for Meddle:
https://groups.google.com/forum/#!searchin/julia-users/meddle|sort:date


W dniu 2015-03-11 o 15:27, Stefan Karpinski pisze:
