### ISSUE TITLE
Handoff request

### ISSUE THREAD

**Issue by ntdef** [JuliaWeb/Meddle.jl#12]
Given that this project has been abandoned, I'd like to take a stab at reviving it. I've been looking at some of the ways that Ring implements Middleware in Clojure, and I think it would be a good fit for some of the Julia functional idiosyncrasies. Pardon me if this was not the right venue, but I would like to request commit access to this repo, @malmaud (or whoever I need to request from).

**Comment by IainNZ** [comment]
@ntdef maybe we can keep things in https://github.com/JuliaWeb/Meddle.jl/pull/11
